// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockAllDevices() {
  return window['go']['main']['App']['BlockAllDevices']();
}

export function BlockUSBPorts() {
  return window['go']['main']['App']['BlockUSBPorts']();
}

export function DiskUsage() {
  return window['go']['main']['App']['DiskUsage']();
}

export function GetCPUPercentage() {
  return window['go']['main']['App']['GetCPUPercentage']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogInfo(arg1) {
  return window['go']['main']['App']['LogInfo'](arg1);
}

export function ManageLogs() {
  return window['go']['main']['App']['ManageLogs']();
}

export function ReadMemoryStats() {
  return window['go']['main']['App']['ReadMemoryStats']();
}

export function UnblockAllDevices() {
  return window['go']['main']['App']['UnblockAllDevices']();
}

export function UnblockUSBPorts() {
  return window['go']['main']['App']['UnblockUSBPorts']();
}

export function WailsInit(arg1) {
  return window['go']['main']['App']['WailsInit'](arg1);
}

export function WriteLog(arg1) {
  return window['go']['main']['App']['WriteLog'](arg1);
}
