// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiskUsage() {
  return window['go']['main']['App']['DiskUsage']();
}

export function GetCPUPercentage() {
  return window['go']['main']['App']['GetCPUPercentage']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogInfo(arg1) {
  return window['go']['main']['App']['LogInfo'](arg1);
}

export function ReadMemoryStats() {
  return window['go']['main']['App']['ReadMemoryStats']();
}

export function WailsInit(arg1) {
  return window['go']['main']['App']['WailsInit'](arg1);
}
